name: helpinghand
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  diacritic: ^0.1.3
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  flutter_tts: ^3.8.3 
  window_size: ^0.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.8
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/helping_hand_logo.jpg
    - assets/images/abuelita.jpg
